version: '3'

services:
  app:
    build: .
    container_name: app
    restart: "always"
    depends_on:
      - db
  
  db:
    image: postgres
    container_name: agenda-db
    restart: "always"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - agendaDB:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  agendaDB:
