[tool.poetry]
name = "agenda"
version = "0.1.0"
description = ""
authors = ["Romulo Sousa <carmosousa20@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
